### ISSUE TITLE
Templates and relations

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1262]
TODO:
- [x] [#1270 Hide Detail Relations handling for Templates](https://github.com/DISSINET/InkVisitor/issues/1270)
- [x] [#1271 Do not allow saving Relations for Templates](https://github.com/DISSINET/InkVisitor/issues/1271)
- [x] [#1272 Do not return Relations with Templates](https://github.com/DISSINET/InkVisitor/issues/1272)
- [ ] [#1273 Handle Relations for Templates](https://github.com/DISSINET/InkVisitor/issues/1273)
- [x] [#1274 Store Relations when a Template is applied](https://github.com/DISSINET/InkVisitor/issues/1274)
- [x] [#2035 Remove warnings](https://github.com/DISSINET/InkVisitor/issues/2035) 

Can templates have relations? What kind of them? And what relations should be copied when using that template in an entity?

IMO, the only relations that may make some sense are Classifications and Superclasses.

**Comment by davidzbiral** [comment]
Templates are currently our way to also prompt editors to fill in some "expected" (1) Metaprops and now also (2) Relations for that template, so in general, we must allow some Relations in them to strengthen convergence in the data.

1) A and C templates:
Let us allow them no Relations (presently and probably also in the future). (In theory they could, nothing ontologically incorrect about it, but this brings more danger than benefit. Because if creating a new A or C, it is exactly because the superclass, event equivalent, etc. are different. That's why a new one is being created.)

2) PLOGESTR templates:
Classification
Related

I was briefly thinking about L template having also SuperordinateLocation (e.g., template "[template of any place in Milan]" with the SuperordinateLocation set to the ID of Milan); while logical and possible, I don't think it is useful. So only those mentioned among PLOGESTR.

**Comment by davidzbiral** [comment]
@Ptrhnk I do not understand this reasoning any more, I think we can close. Templates can have any relations that their entity type is allowed to have.
