### ISSUE TITLE
Territory-based validation rules

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1924]
With CASTEMO being understood more and more as potential training data for providing AI-powered assistance (and thus truly stand up to the CA [computer-assisted] in the CASTEMO name), it turns out that projects need to be able to implement a much more coordinated way of classifying statements, rather than thinking only along the lines of a large set of rules to get these classifications completely in the bottom-up way in DB2 (Neo4j).

We have a precise way to mark negative logic and modality, but we need to introduce a way how to _require_ from coders explicit classifications of any statement in a given T (i.e. it is T-based, inherited down the line; not only root T, even a subT can have a rule, inherited then to its sub-Ts; this is closely related to structured data collection protocols: #1152). 

Thus, we need an interface - probably the same where we will describe the data collection protocols in more textual notes, but part of it in structured form - where we will **define required tags for each statement in that T and its subTs**. Probably it should be a special section of Detail section of the T model.

For instance, in DISSINET, we need to be able to require from coders:
- trial action binary classification (is this a trial interaction or not?)
- dissidence binary classification (does this action constitute suspicion of heresy or not).
And we need a "detail" - description of the tag variable which will be displayed on mouseover in the Statement editor.

In statement editor, the required S fields would probably be displayed before the "free" tags.
This statement attribute will be part of validation (i.e. notify editor if empty).

Sometimes we want binary y/n, sometimes we want categorical with suggester slot for Concept, Concept | Value.... this definition of what the given statement variable can take in could be very similar to Action entity type valency. Yes. Binary y/n will be one option, excluding the others, probably a button switch between Binary (values: yes, no, displayed as a button-switch in Statement Editor) and Entity (displayed as a suggester in the Statement Editor). With Entity choice, in the definition of the required variables (probably in T Detail), the field to define the entity type required here should be the same as Action entity type valency field, where the user will define what can be in. Also "empty" value will be in the select, which will then define that if the classification is empty, it does not produce an error notification, i.e. it can be empty. A binary can never be left empty - always produces validation error notification if nothing is chosen.

Child issues:
  - [x] #1985 - for extending the T model with Protocol interface
  - [x] #1976 - for integration of  validations on BE
  - [x] #1977 - for implementing the protocols assignment on FE and displaying the warnings in statement editor

**Comment by adammertel** [comment]
I would pick a name different from _classification_ which is currently a type of relation in CASTEMO. How about _local attribute_?

My suggestion for the data model would be (not talking about the UI at this point):

 - **name** - displayed name of the attribute
 - **detail** - more detailed information is shown in tooltip
 - **required** - not sure if two values only (mandatory, optional) or we should go even deeper (error, warning, at least one per T should be filled in,...)
 - **value type** - to me, this could be a custom list of plain text values (yes / maybe / no), entity type (C + E), number (numerical values), boolean (just true and false)
    - _but could be easily replaced by defining all values by the entities only (e.g., replacing yes by V entity with label yes...)_
 - **values** - the list of values that are allowed to be assigned, based on the value type selected.
 
 @davidzbiral, what do you think about this? Do you miss something?

**Comment by davidzbiral** [comment]
@adammertel This sounds about right. What is the purpose of having value type, and list of values? Would it not be enough to have only the list of allowed values, which would then show in the suggester? I think that the solution with allowed Concepts and Values, listed as tags through an entity suggester, is the right one.
For instance, if we say that C "statement type" is one of the followed attributes of statements (we are talking about statements here), then we would list e.g. the following allowed values: C "interaction at trial" and C "statement about the past", and C "other". 
Similarly, we could have a required (for this T) Statement metaprop with proptype C "degree on the scale of resistance and compliance", and values C "high degree of resistance", C "medium degree of resistance", C "low degree of resistance", C "partial compliance", C "full compliance", and C "" (this is an example, we probably won't do this - just an example of non-binary classifications).

This structure not only resembles but actually _is_ one of a property, and generally it is good not to multiply objects above necessity. Thus, I would see it as a metaproperty of the statement, not a new thing. But a property which would:
1. appear pre-filled with property type,
2. allow only recommended values (i.e. if this proptype appears as metaprop of a statement in this T, take only these values),
3. lead to validation msg on the statement.
In Statements, we rarely open detail, but sometimes we do, e.g. to fill in things such as "anti-clerical statement", and this we do through CLA. We need to remember that relations are, conceptually, nothing but reserved props with fixed proptype - ones very typical for whom we wanted to ensure stability across CASTEMO database instances ~ InkVisitor deploys. But here, we need both slots, so metaprop seems the right solution, and we don't need to introduce any new object / relation, what you think?
The only problem is how to rather help the user fill this in than stress and bother him with an error message. 

An alternative solution is really CLA: i.e. have Cs such as "statement on interaction at trial", and "statement on something else than interaction at trial", set these in the T protocol as a set, and output a validation error if these are not filled in (again, both the nice thing and problem is the absence of save button - I am _not_ suggesting to introduce it!), i.e. the validation messages are displayed quite early on. 

I think I prefer metaprops over CLA for those cases. Yes, it is in CLA that things such as "anti-clerical statement" or "invective against the inquisitor" would appear, but creating e.g. a whole scale such as "statement signalling high degree of resistance" (and medium and low) results in Concepts whose label is a little clumsy, and it is less clear what are the recommended values. 

If you have any comment on metaprop vs. CLA, tell me. In any case, I would not introduce a new thing, because we have at least two ways how to do it already. (I drop my note on mouseover, this is not necessary.)

In both solutions, our problem is how to make it less invisible, because normally one does not open the Detail of a statement.

I think **metaprops are better**, because they allow to develop a **more general solution: required metaprops, _optionally_ with a fixed list of values**: for any T, setting what metaprops are required for any entity appearing under it. E.g., make the "sex" metaproperty required in Persons in a T, and in similar way, in this T, make something required for statements. Of course, it is not the person entity or the statement itself which should shout with validation error, e.g. if displayed in search or a T, but for a Statement a validation error in Editor if the Statement is within a Territory which requires some metaprop which is not filled in. So if I say that in Seila, I require sex metaprop in Persons and only allow values "male" and "female", and I use a Person in a register statement which has a Person as actant not having this metaprop (propvalue and proptype) filled in, a validation error in the Editor, saying "A metaproperty required for this Territory is missing in [+ clickable entity tags]" (if propvalue is empty or prop is missing altogether) or "A property value used in this statement does not match the protocol for this Territory" (e.g. if this person has C sex C "non-binary").

**Comment by adammertel** [comment]
To summarize. 
 - Ts will have mandatory entity-level Props for underlying statements. 
 - Statement-level Props sections could then be moved to the Editor, and a warning message should be associated with this section so the user can see the message at the right time.
 - It's not necessary to handle both `value type` and `values` in the data model as the values could be only Entities (either any entity of a certain class/classes or a definite list of entities entered by the user).

**Comment by davidzbiral** [comment]
@adammertel I confirm all this, thanks for the summary.
> Statement-level Props sections could then be moved to the Editor
Great solution I think, if it is not troubling that this can be done at two places (Detail and Statement Editor - or do you plan to remove it from Detail in the case of Statements - i.e. in the GUI, not talking about the data model).

detail (potentially useful when we find a way how to display it): I think we might drop this for now, because the instruction would be implicitly present in the list of recommended values.

The rules are entity-type-based. I.e. metaprop rules for each entity type can be set under any T.

The question is whether the list should be recommended or enforced. I think we could have two levels in the settings under a T (and even the whole database, i.e. root): if it is a required list of possible propvalues, then no other value would be allowed in that proptype for the given entity; if it is recommended, the entities in the propvalue list would still show first in suggester, but the GUI would take also other values, perhaps displaying a warning after selecting it, that it is not part of the list, but allowing it. 
So I think it could be a switch when setting each metaprop at the T level: for each metaprop set under the T protocol (let's call it protocol, which has its textual parts / free fields, and these more structured rules), the user would select whether the list of values (entered through a suggester) is final or recommended, e.g. by values in the radio button: "only allow these entities" / "suggest these entities but also allow any other (with warning)". Something like that. For each metaprop separately.

I hope it is not too complicated :-) 

BTW I am reminding that perhaps Adam & David are going in the direction of seeing metaprops more as entities in its own right, which could influence our thinking about it - but perhaps not so important in fact for the solution of this issue.

**Comment by adammertel** [comment]
Added a new section to the [warning document](https://docs.google.com/document/d/1pmsCjNLHAOA58gVrwV64Qfsp-9wO4kZoXbtyjViMuQA/edit)
![image](https://github.com/DISSINET/InkVisitor/assets/12932677/d6518d6d-01ee-459c-bc35-2d5296bd2181)

**Comment by adammertel** [comment]
Here is a draft of how the Protocol assigning might look in the Detail box
![image](https://github.com/DISSINET/InkVisitor/assets/12932677/d190a7ed-a6f0-4cd2-a922-5808fd2a7bcf)

**Comment by adammertel** [comment]
Created two child issues:
 #1976 - for integration of protocols and the relevant validations on BE
 #1977 - for implementing the protocols assignment on FE and displaying the warnings in statement editor

**Comment by davidzbiral** [comment]
@adammertel The draft looks nice, only I need to understand how it will work in practice, i.e. what will be the conditions which will trigger error. How the app will know when to trigger error? How does it know what the protocol relates to? E.g. that it concerns a (1) CLA, and namely, (2) CLA of Statements?

**Comment by adammertel** [comment]
Created #1981

**Comment by adammertel** [comment]
@davidzbiral thanks. 
I think the "recommended/mandatory" switch is missing here, need to add :/
Regarding the note
> How does it know what the protocol relates to
I thought that all protocols defines rules only for the 1st level meta props. Are we going to used them for IDE and CLA as well? Or anything else as well?

**Comment by davidzbiral** [comment]
@adammertel : The original request was actually on CLA (meta level), not on metaprops. (Now of course, CLA is hiddenly a metaprop with a required, pre-set proptype, but that's a different and more ontological issue.) 

But we need to think about it in a much broader framework:
For a given Territory, we need to set rules per entity type.
There are three components of the condition:
1) Entity type it concerns (e.g. Statement).
2a) Relation type it concerns.
2b) (If relation = in-statement prop or metaprop, then optionally) define proptype which triggers the validation
3) Allowed value entity type (if applicable - can be empty) - propvalue in props, target in CLA etc.
4) Positive list of allowed entities (if applicable - can be empty).

For instance: when coding a medieval inquisition record, as project manager, in this territory, I want to only allow values of "gender" var. as "male" and "female", but in a document on LGBTQ+ people, I want to allow more values.
So I need:
1) For entity type person...
1b) (optional) If it has CLA relation with target "human person"
2a) and it gets a metaprop relation...
2b) with proptype "gender"
3) (optional: allow only C entity type as propvalue)
4) and allow only value C male, C female.

What ties we need to capture, i.e. they should be part of the menu:
* metaprops
* in-statement props
* CLA
* in-statement CLA
* reference

Of course, the Detail-edited parts are contextual, i.e. the Detail is not invalid, but the use of this entity in a Statement (incl. any fields, e.g. in-statement props) of the given T. I.e. the validation warning is never displayed on Detail, but on Statement of the given T.

The entity type (no. 1) also must allow value "Any", i.e. the rule will concern all entities. E.g., if somebody is transferring from a relational database and wants to check that all entities have a Reference to the ID in the previous db. It will be rare, with very specific uses, but why not allow it.

Another use case: in a T (data collection campaign), or the root, i.e. the whole deploy (owner), I want that every Person has "sex" filled in. The root rules (whole deploy) are _not_ contextual - these I think should be displayed in Detail, i.e. the entity per se is not yet valid.

We will often also need a condition which says that any value is permitted, but the metaprop or CLA or ref is required - i.e. not list values, but set that the metaprop must be there. I guess it can be done by leaving the list of allowed values empty.


Examples of use of the global settings:
* I want that all manuscripts have physical dimensions in cm filled in. => I set for O which are CLAssified as C "manuscript" that they must have a metaprop which says C "height in cm", and with non-empty value.

I think we don't need recommended / required under this setting - all will only trigger warning. In global root rules, they will be displayed in Detail, just as valency validations iN Actions. In contextual T-level, they will be displayed on Statements which use an entity invalid by the standards set for that T.

**Comment by adammertel** [comment]
Thanks @davidzbiral , I have updated the Figma design and will extend the model based on this. Warnings will be much more complicated considering all the use-cases, maybe we should structure them in more depths (?).

![image](https://github.com/DISSINET/InkVisitor/assets/12932677/29a6eaa7-78ef-41e3-94f2-ec03e44a93ef)

**Comment by adammertel** [comment]
New design based on our last discussion
![image](https://github.com/DISSINET/InkVisitor/assets/12932677/4afed3db-673e-43c6-8250-cacaaa12133d)

**Comment by davidzbiral** [comment]
@adammertel Not bad, just:
- From the design, it is unclear that the "classified as" and "prop type" multiple has the OR logic, not the AND logic. It should be clear.
- meta vs. in-statement seems to be a switch, while we were talking about the possibility of chosing also both in one stroke, i.e. a check list rather than radio button.
- We need to get the terminology right: you devs talk about entity classes, but the documentation of the conceptual data model has the notion of "entity type"; ties are my ad hoc attempt but did we not use some better expression to encompass together Relations, Props and References together? Finally, prop is jargon, please write in full "Property".
- The generalistic solution fails to capture that if specific allowed values are listed, it clashes with allowed type. The user can only set one or the other, not both at a time (thus we don't need to solve conflict, but also it would be meaningful to set value's entity type if a positive list is given). So this should be two mutually exclusive possibilities, never both at a time.

**Comment by davidzbiral** [comment]
@adammertel Did we not say we will not call it protocol? It is somehow a part of it, but is it not a little confusing? I must think.

**Comment by adammertel** [comment]
Thank you for the comment. I will reconsider the design.
Regarding the naming of the section, it's up to you. You would suggest using something else than simple "validation" as it mihmght not be clear (?)

**Comment by davidzbiral** [comment]
I was suggesting "Validation rules", not just "Validation", so unless you have a better proposal, let's go with that.

I edited the post now - some parts were a little unclear.
